# Generated by Django 5.2.7 on 2025-12-06 21:04

import core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('wywoz_smieci', 'Wywóz śmieci'), ('ubezpieczenie', 'Ubezpieczenie'), ('podatek', 'Podatek od nieruchomości'), ('energia_wspolna', 'Energia części wspólnych')], max_length=100, verbose_name='Typ kosztu')),
                ('cost_per_person', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Koszt / osobę')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stała kwota')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data wejścia w życie')),
            ],
            options={
                'verbose_name': 'Koszt Stały',
                'verbose_name_plural': 'Koszty Stałe',
            },
        ),
        migrations.CreateModel(
            name='Lokal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text="Np. '3a', '12'", max_length=10, unique=True, verbose_name='Numer mieszkania')),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wielkość (m²)')),
                ('description', models.TextField(blank=True, help_text='Opis wyposażenia, stanu lokalu.', verbose_name='Opis zawartości')),
                ('meter_count_quantity', models.IntegerField(blank=True, null=True, verbose_name='Ilość liczników (ogółem)')),
            ],
            options={
                'verbose_name': 'Lokal',
                'verbose_name_plural': 'Lokale',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('pesel', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[core.validators.validate_pesel], verbose_name='PESEL')),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nr Paszportu')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adres e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('wlasciciel', 'Właściciel'), ('lokator', 'Lokator'), ('byly_lokator', 'Były Lokator'), ('budynek', 'Budynek')], max_length=50, verbose_name='Rola')),
            ],
            options={
                'verbose_name': 'Użytkownik',
                'verbose_name_plural': 'Użytkownicy',
            },
        ),
        migrations.CreateModel(
            name='LocalPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lokale_photos/', verbose_name='Zdjęcie')),
                ('photo_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data wykonania zdjęcia')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Opis zdjęcia')),
                ('lokal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.lokal', verbose_name='Lokal')),
            ],
            options={
                'verbose_name': 'Zdjęcie Lokalu',
                'verbose_name_plural': 'Zdjęcia Lokalu',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signing_date', models.DateField(verbose_name='Data zawarcia')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia najmu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia najmu')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota czynszu (nominalna)')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota kaucji')),
                ('type', models.CharField(choices=[('umowa', 'Umowa'), ('aneks', 'Aneks')], default='umowa', max_length=20, verbose_name='Rodzaj')),
                ('additional_info', models.TextField(blank=True, verbose_name='Informacje dodatkowe')),
                ('number_of_occupants', models.IntegerField(verbose_name='Liczba osób zamieszkujących')),
                ('old_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aneks_agreements', to='core.agreement', verbose_name='Stara umowa (dla aneksów)')),
                ('lokal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='core.lokal', verbose_name='Lokal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='core.user', verbose_name='Użytkownik (Lokator)')),
            ],
            options={
                'verbose_name': 'Umowa',
                'verbose_name_plural': 'Umowy',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Numer seryjny')),
                ('type', models.CharField(choices=[('woda_zimna', 'Woda Zimna'), ('woda_ciepla', 'Woda Ciepła'), ('energia', 'Energia'), ('gaz', 'Gaz'), ('co', 'Centralne Ogrzewanie')], max_length=50, verbose_name='Typ licznika')),
                ('status', models.CharField(choices=[('aktywny', 'Aktywny'), ('nieaktywny', 'Nieaktywny')], default='aktywny', max_length=20, verbose_name='Status')),
                ('local_meter_number', models.IntegerField(blank=True, help_text='Np. [1, 2] dla wody', null=True, verbose_name='Nr licznika w mieszkaniu')),
                ('lokal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters', to='core.lokal', verbose_name='Lokal')),
            ],
            options={
                'verbose_name': 'Licznik',
                'verbose_name_plural': 'Liczniki',
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='Data odczytu')),
                ('value', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Wartość odczytu (m³, kWh)')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meter', verbose_name='Licznik')),
            ],
            options={
                'verbose_name': 'Odczyt Licznika',
                'verbose_name_plural': 'Odczyty Liczników',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Wpłata (przychód) to kwota dodatnia, wypłata (koszt) to kwota ujemna.', max_digits=10, verbose_name='Kwota [+/-]')),
                ('posting_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data księgowania')),
                ('type', models.CharField(choices=[('czynsz', 'Czynsz'), ('media', 'Opłaty za media'), ('kaucja', 'Kaucja'), ('naprawy', 'Naprawy / Remonty'), ('smieci', 'Wywóz śmieci'), ('wspolnota', 'Potrzeby kamienicy'), ('energia_klatka', 'Energia klatka'), ('energia_m8', 'Energia m8'), ('wyplata', 'Wypłaty'), ('oplaty_bankowe', 'Opłaty bankowe'), ('sprzatanie', 'Sprzątanie'), ('inne', 'Inne')], max_length=50, verbose_name='Typ transakcji')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('lokal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.lokal', verbose_name='Lokal')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.user', verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Transakcja Finansowa',
                'verbose_name_plural': 'Transakcje Finansowe',
                'ordering': ['-posting_date'],
            },
        ),
        migrations.CreateModel(
            name='RentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(help_text='Dotyczy miesiąca, np. 2025-01-01', verbose_name='Miesiąc płatności')),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota do zapłaty')),
                ('description', models.CharField(blank=True, help_text="Np. 'Korekta za połowę miesiąca'", max_length=255, verbose_name='Opis')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedule', to='core.agreement', verbose_name='Umowa')),
            ],
            options={
                'verbose_name': 'Harmonogram Czynszu',
                'verbose_name_plural': 'Harmonogramy Czynszów',
                'unique_together': {('agreement', 'year_month')},
            },
        ),
    ]
