# Generated by Django 5.2.8 on 2025-12-07 14:00

from django.db import migrations
from datetime import date

def create_test_data(apps, schema_editor):
    """
    Tworzy dane testowe: 2 lokale, 3 użytkowników, 4 liczniki i 2 umowy.
    """
    User = apps.get_model('core', 'User')
    Lokal = apps.get_model('core', 'Lokal')
    Meter = apps.get_model('core', 'Meter')
    Agreement = apps.get_model('core', 'Agreement')

    # --- Krok 1: Utwórz 2 Lokale ---
    lokal1 = Lokal.objects.create(
        unit_number='1A',
        size_sqm=45.50,
        description='Mieszkanie dwupokojowe na parterze.',
        meter_count_quantity=2
    )
    lokal2 = Lokal.objects.create(
        unit_number='2B',
        size_sqm=62.00,
        description='Mieszkanie trzypokojowe na piętrze.',
        meter_count_quantity=2
    )

    # --- Krok 2: Utwórz 3 Użytkowników ---
    user1 = User.objects.create(
        name='Jan',
        lastname='Kowalski',
        email='jan.kowalski@example.com',
        role='lokator',
        pesel='85010112345'
    )
    user2 = User.objects.create(
        name='Anna',
        lastname='Nowak',
        email='anna.nowak@example.com',
        role='lokator',
        pesel='92051054321'
    )
    user3 = User.objects.create(
        name='Piotr',
        lastname='Wiśniewski',
        email='piotr.wisniewski@example.com',
        role='wlasciciel',
        pesel='78032067890'
    )

    # --- Krok 3: Utwórz po 2 liczniki dla każdego lokalu ---
    # Liczniki dla Lokalu 1A
    Meter.objects.create(
        serial_number='WODA-Z-1A-001',
        type='woda_zimna',
        status='aktywny',
        lokal=lokal1,
        local_meter_number=1
    )
    Meter.objects.create(
        serial_number='WODA-C-1A-002',
        type='woda_ciepla',
        status='aktywny',
        lokal=lokal1,
        local_meter_number=2
    )

    # Liczniki dla Lokalu 2B
    Meter.objects.create(
        serial_number='WODA-Z-2B-003',
        type='woda_zimna',
        status='aktywny',
        lokal=lokal2,
        local_meter_number=1
    )
    Meter.objects.create(
        serial_number='ENERGIA-2B-004',
        type='energia',
        status='aktywny',
        lokal=lokal2,
        local_meter_number=2
    )

    # --- Krok 4: Utwórz 2 umowy dla pierwszych dwóch użytkowników ---
    Agreement.objects.create(
        user=user1,
        lokal=lokal1,
        signing_date=date(2024, 1, 15),
        start_date=date(2024, 2, 1),
        end_date=date(2025, 1, 31),
        rent_amount=2500.00,
        deposit_amount=2500.00,
        type='umowa',
        number_of_occupants=2
    )
    Agreement.objects.create(
        user=user2,
        lokal=lokal2,
        signing_date=date(2023, 6, 1),
        start_date=date(2023, 6, 1),
        rent_amount=3200.00,
        deposit_amount=3200.00,
        type='umowa',
        number_of_occupants=3
    )

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_data),
    ]
