# Generated by Django 5.2.8 on 2025-12-07 15:00

from django.db import migrations
from datetime import date

def create_historical_data(apps, schema_editor):
    """
    Tworzy dane historyczne za 3 miesiące wstecz dla istniejących obiektów:
    - Odczyty liczników
    - Harmonogramy i płatności czynszu
    """
    Meter = apps.get_model('core', 'Meter')
    MeterReading = apps.get_model('core', 'MeterReading')
    Agreement = apps.get_model('core', 'Agreement')
    RentSchedule = apps.get_model('core', 'RentSchedule')
    FinancialTransaction = apps.get_model('core', 'FinancialTransaction')

    # Pobierz dzisiejszą datę do obliczeń
    today = date(2025, 12, 7)
    
    # --- Krok 1: Wygeneruj odczyty liczników za 3 miesiące wstecz ---
    all_meters = Meter.objects.all()
    if not all_meters.exists():
        return # Jeśli nie ma liczników, zakończ

    for meter in all_meters:
        # Przykładowe wartości początkowe
        base_value = 100 if 'WODA' in meter.serial_number else 1500
        # Generuj odczyty na pierwsze dni 3 poprzednich miesięcy
        for i in range(1, 4):
            month = today.month - i
            year = today.year
            if month <= 0:
                month += 12
                year -= 1
            
            reading_date = date(year, month, 1)
            # Prosta logika zwiększania wartości co miesiąc
            reading_value = base_value + (3 - i) * (10 if 'WODA' in meter.serial_number else 150)

            MeterReading.objects.create(
                meter=meter,
                reading_date=reading_date,
                value=reading_value
            )

    # --- Krok 2: Wygeneruj harmonogramy i transakcje czynszowe ---
    all_agreements = Agreement.objects.all()
    if not all_agreements.exists():
        return # Jeśli nie ma umów, zakończ

    for agreement in all_agreements:
        for i in range(1, 4):
            month = today.month - i
            year = today.year
            if month <= 0:
                month += 12
                year -= 1

            payment_month = date(year, month, 1)
            
            # a) Utwórz wpis w harmonogramie czynszów
            RentSchedule.objects.create(
                agreement=agreement,
                year_month=payment_month,
                due_amount=agreement.rent_amount,
                description=f"Czynsz za {payment_month.strftime('%B %Y')}"
            )

            # b) Utwórz symulację wpłaty czynszu (datowana na okolice 10. dnia miesiąca)
            payment_date = date(year, month, 10)
            FinancialTransaction.objects.create(
                user=agreement.user,
                lokal=agreement.lokal,
                amount=agreement.rent_amount, # Wpłata (kwota dodatnia)
                posting_date=payment_date,
                description=f"Wpłata czynszu za {payment_month.strftime('%B %Y')}"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_test_data'),
    ]

    operations = [
        migrations.RunPython(create_historical_data),
    ]
