# Generated by Django 6.0 on 2025-12-14 15:58

import core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_historical_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AddField(
            model_name='lokal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
        migrations.CreateModel(
            name='HistoricalAgreement',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('signing_date', models.DateField(verbose_name='Data zawarcia')),
                ('start_date', models.DateField(verbose_name='Data rozpoczęcia najmu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data zakończenia najmu')),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota czynszu (nominalna)')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kwota kaucji')),
                ('type', models.CharField(choices=[('umowa', 'Umowa'), ('aneks', 'Aneks')], default='umowa', max_length=20, verbose_name='Rodzaj')),
                ('additional_info', models.TextField(blank=True, verbose_name='Informacje dodatkowe')),
                ('number_of_occupants', models.IntegerField(verbose_name='Liczba osób zamieszkujących')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lokal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.lokal', verbose_name='Lokal')),
                ('old_agreement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.agreement', verbose_name='Stara umowa (dla aneksów)')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.user', verbose_name='Użytkownik (Lokator)')),
            ],
            options={
                'verbose_name': 'historical Umowa',
                'verbose_name_plural': 'historical Umowy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLokal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('unit_number', models.CharField(db_index=True, help_text="Np. '3a', '12'", max_length=10, verbose_name='Numer mieszkania')),
                ('size_sqm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Wielkość (m²)')),
                ('description', models.TextField(blank=True, help_text='Opis wyposażenia, stanu lokalu.', verbose_name='Opis zawartości')),
                ('meter_count_quantity', models.IntegerField(blank=True, null=True, verbose_name='Ilość liczników (ogółem)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Lokal',
                'verbose_name_plural': 'historical Lokale',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię')),
                ('lastname', models.CharField(max_length=100, verbose_name='Nazwisko')),
                ('pesel', models.CharField(blank=True, db_index=True, max_length=11, null=True, validators=[core.validators.validate_pesel], verbose_name='PESEL')),
                ('passport_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Nr Paszportu')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Adres e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('wlasciciel', 'Właściciel'), ('lokator', 'Lokator'), ('byly_lokator', 'Były Lokator'), ('budynek', 'Budynek')], max_length=50, verbose_name='Rola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Użytkownik',
                'verbose_name_plural': 'historical Użytkownicy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
