# Generated by Django 6.0 on 2025-12-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agreement_is_active_lokal_is_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtransaction',
            name='type',
        ),
    ]
