# Generated by Django 6.0 on 2025-12-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_financialtransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='contractor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontrahent'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID Transakcji'),
        ),
    ]
