# Generated by Django 6.0 on 2025-12-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_manual_drop_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='title',
            field=models.CharField(blank=True, choices=[('czynsz', 'czynsz'), ('oplaty', 'opłaty'), ('oplata_bankowa', 'opłata bankowa'), ('energia_klatka', 'energia klatka'), ('energia_m8', 'energię M8'), ('na_potrzeby_kamienicy', 'na potrzeby kamienicy'), ('naprawy_remonty', 'naprawy/remonty'), ('oplata_za_wode', 'opłata za wodę'), ('wywoz_smieci', 'wywóz śmieci'), ('sprzatanie', 'sprzątanie'), ('ogrodnik', 'ogrodnik'), ('ubezpieczenie', 'ubezpieczenie'), ('internet_telefon', 'internet/telefon'), ('elektryk', 'elektryk'), ('kominiarz', 'kominiarz'), ('piece_co', 'piece co'), ('podatek', 'podatek'), ('oplata_nie_stanowiaca_kosztu', 'opłata nie stanowiąca kosztu')], max_length=100, null=True, verbose_name='Tytułem'),
        ),
    ]
