# Generated by Django 6.0 on 2025-12-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_financialtransaction_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, unique=True, verbose_name='Słowo kluczowe')),
                ('title', models.CharField(choices=[('czynsz', 'czynsz'), ('oplaty', 'opłaty'), ('oplata_bankowa', 'opłata bankowa'), ('energia_klatka', 'energia klatka'), ('energia_m8', 'energię M8'), ('na_potrzeby_kamienicy', 'na potrzeby kamienicy'), ('naprawy_remonty', 'naprawy/remonty'), ('oplata_za_wode', 'opłata za wodę'), ('wywoz_smieci', 'wywóz śmieci'), ('sprzatanie', 'sprzątanie'), ('ogrodnik', 'ogrodnik'), ('ubezpieczenie', 'ubezpieczenie'), ('internet_telefon', 'internet/telefon'), ('elektryk', 'elektryk'), ('kominiarz', 'kominiarz'), ('piece_co', 'piece co'), ('podatek', 'podatek'), ('oplata_nie_stanowiaca_kosztu', 'opłata nie stanowiąca kosztu')], max_length=100, verbose_name='Tytuł')),
            ],
            options={
                'verbose_name': 'Reguła kategoryzacji',
                'verbose_name_plural': 'Reguły kategoryzacji',
            },
        ),
    ]
