# Generated by Django 6.0 on 2025-12-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categorizationrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorizationrule',
            name='keyword',
        ),
        migrations.AddField(
            model_name='categorizationrule',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='Słowa kluczowe (oddzielone przecinkami)'),
            preserve_default=False,
        ),
    ]
