# Generated by Django 6.0 on 2025-12-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_categorizationrule_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LokalAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(help_text='Np. nazwisko, fragment opisu, numer konta bankowego', max_length=255, verbose_name='Słowa kluczowe / Nr konta')),
                ('lokal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.lokal', verbose_name='Przypisany Lokal')),
            ],
            options={
                'verbose_name': 'Reguła przypisania lokalu',
                'verbose_name_plural': 'Reguły przypisania lokalu',
            },
        ),
    ]
