# Generated by Django 5.0.4 on 2025-12-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_lokalassignmentrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='type',
            field=models.CharField(choices=[('cold_water', 'Woda zimna'), ('hot_water', 'Woda ciepła'), ('electricity', 'Energia elektryczna'), ('gas', 'Gaz')], max_length=50, verbose_name='Typ licznika'),
        ),
    ]