# Generated by Django 5.0.4 on 2025-12-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_meter_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lokal',
            name='meter_count_quantity',
        ),
        migrations.AlterField(
            model_name='meter',
            name='type',
            field=models.CharField(choices=[('cold_water', 'Woda zimna'), ('hot_water', 'Woda ciepła'), ('electricity', 'Energia elektryczna'), ('gas', 'Gaz'), ('heat', 'Energia cieplna')], max_length=50, verbose_name='Typ licznika'),
        ),
    ]
