# Generated by Django 6.0 on 2025-12-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20251226_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallokal',
            name='meter_count_quantity',
        ),
    ]
