# Generated by Django 6.0 on 2025-12-26 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_historicallokal_meter_count_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixedcost',
            options={'ordering': ['-effective_date'], 'verbose_name': 'Reguła Naliczania Opłat', 'verbose_name_plural': 'Reguły Naliczania Opłat'},
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='cost_per_person',
        ),
        migrations.RemoveField(
            model_name='fixedcost',
            name='cost_type',
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='calculation_method',
            field=models.CharField(choices=[('per_person', 'Od osoby'), ('fixed_amount', 'Stała kwota (dla całej nieruchomości)'), ('per_unit', 'Za jednostkę (np. m³ wody)')], default='fixed_amount', max_length=50, verbose_name='Metoda obliczeń'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='meter_type',
            field=models.CharField(blank=True, choices=[('cold_water', 'Woda zimna'), ('hot_water', 'Woda ciepła'), ('electricity', 'Energia elektryczna'), ('gas', 'Gaz'), ('heat', 'Energia cieplna')], max_length=50, null=True, verbose_name="Typ licznika (dla opłat 'za jednostkę')"),
        ),
        migrations.AddField(
            model_name='fixedcost',
            name='name',
            field=models.CharField(default='fixed_amount', max_length=150, verbose_name='Nazwa reguły'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fixedcost',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Kwota od osoby, stała kwota lub cena za jednostkę', max_digits=10, verbose_name='Wartość'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MonthlyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='Pierwszy dzień miesiąca, którego dotyczy naliczenie, np. 2025-01-01', verbose_name='Miesiąc naliczenia')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Czynsz')),
                ('fixed_fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Opłaty stałe (np. śmieci)')),
                ('water_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Koszt wody')),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Suma naliczenia')),
                ('description', models.TextField(blank=True, verbose_name='Opis/Notatki do naliczenia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_charges', to='core.agreement', verbose_name='Umowa')),
            ],
            options={
                'verbose_name': 'Naliczenie Miesięczne',
                'verbose_name_plural': 'Naliczenia Miesięczne',
                'ordering': ['-month_year', 'agreement'],
                'unique_together': {('agreement', 'month_year')},
            },
        ),
    ]
