# Generated by Django 6.0 on 2025-12-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_fixedcost_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallokal',
            name='size_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Wielkość (m²)'),
        ),
        migrations.AlterField(
            model_name='lokal',
            name='size_sqm',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Wielkość (m²)'),
        ),
    ]
