# Generated by Django 6.0 on 2025-12-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_historicallokal_size_sqm_alter_lokal_size_sqm'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Przetworzono'), ('UNPROCESSED', 'Nieprzetworzono'), ('CONFLICT', 'Konflikt')], default='UNPROCESSED', max_length=20, verbose_name='Status'),
        ),
    ]
