# Generated by Django 6.0 on 2025-12-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_financialtransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='processing_log',
            field=models.TextField(blank=True, null=True, verbose_name='Log przetwarzania'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Przetworzono automatycznie'), ('UNPROCESSED', 'Nieprzetworzono'), ('CONFLICT', 'Konflikt reguł'), ('MANUALLY_EDITED', 'Edytowano ręcznie')], default='UNPROCESSED', max_length=20, verbose_name='Status'),
        ),
    ]
