# Generated by Django 6.0 on 2025-12-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_financialtransaction_processing_log_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialtransaction',
            name='processing_log',
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('PROCESSED', 'Przetworzono'), ('UNPROCESSED', 'Nieprzetworzono'), ('CONFLICT', 'Konflikt')], default='UNPROCESSED', max_length=20, verbose_name='Status'),
        ),
    ]
