# Generated by Django 6.0 on 2025-12-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_financialtransaction_processing_log_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterCostOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField(help_text='Pierwszy dzień pierwszego miesiąca okresu, np. 2025-01-01 dla Styczeń-Luty', unique=True, verbose_name='Początek okresu rozliczeniowego')),
                ('overridden_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ręcznie wprowadzona kwota rachunku za wodę')),
                ('overridden_total_consumption', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Ręcznie wprowadzone całkowite zużycie wody (m³)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ręczne Ustawienie Kosztu Wody',
                'verbose_name_plural': 'Ręczne Ustawienia Kosztów Wody',
                'ordering': ['-period_start_date'],
            },
        ),
    ]
