# Generated by Django 6.0.1 on 2026-01-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_watercostoverride'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watercostoverride',
            options={'ordering': ['-period_start_date'], 'verbose_name': 'Rozliczenie wody', 'verbose_name_plural': 'Rozliczenia wody'},
        ),
        migrations.AddField(
            model_name='agreement',
            name='balance_start_date',
            field=models.DateField(blank=True, help_text='Data, na którą przypisane jest saldo początkowe.', null=True, verbose_name='Data salda początkowego'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo na początek okresu rozliczeniowego w aplikacji.', max_digits=10, verbose_name='Saldo początkowe'),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='balance_start_date',
            field=models.DateField(blank=True, help_text='Data, na którą przypisane jest saldo początkowe.', null=True, verbose_name='Data salda początkowego'),
        ),
        migrations.AddField(
            model_name='historicalagreement',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo na początek okresu rozliczeniowego w aplikacji.', max_digits=10, verbose_name='Saldo początkowe'),
        ),
    ]
