# Generated by Django 5.2.7 on 2026-01-31 19:44

from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User.objects.create_superuser('admin@example.com', 'admin@example.com', 'admin')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_watercostoverride_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]