# Generated by Django 5.2.7 on 2026-02-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='category',
            field=models.CharField(blank=True, choices=[('waste', 'Wywóz śmieci'), ('other', 'Inne')], help_text='Określa rodzaj opłaty. Wymagane do automatycznych obliczeń.', max_length=50, null=True, verbose_name='Kategoria'),
        ),
    ]
