# Generated by Django 5.2.7 on 2026-02-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fixedcost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlycharge',
            name='total_charge',
        ),
    ]
