# Generated by Django 6.0 on 2026-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_monthlycharge_total_charge_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='processing_log',
            field=models.TextField(blank=True, null=True, verbose_name='Log przetwarzania'),
        ),
    ]
