# Generated by Django 6.0 on 2026-05-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_add_processing_log_to_financialtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Zweryfikowano ręcznie'),
        ),
    ]
