# Generated by Django 5.0.14 on 2025-12-14 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_agreement_is_active_lokal_is_active_user_is_active_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='lokal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lokal', verbose_name='Lokal'),
        ),
    ]
